# theme 
remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: air
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Paris"

# Site settings
locale: "fr-FR"
name: "Pierre-Emmanuel MERCIER"
title: "Ace Blog"
search: true
breadcrumbs: true 
include:
  - _pages

# Social Sharing
twitter:
  username: "lim_ace"

# Site Author
author:
  name             : "Pierre-Emmanuel MERCIER"
  location         : "Bordeaux, France"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lim_ace"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/acesyde"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lim_ace"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/acesyde"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache