# theme 
remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: dark

# Site settings
locale: "fr-FR"
title: "Ace Blog"
name: "Pierre-Emmanuel MERCIER"

plugins:
  - jekyll-include-cache